// AUTO-GENERATED by scripts/generateAudioMap.js — DO NOT EDIT MANUALLY
// Run: node scripts/generateAudioMap.js  (or npm run gen:audio)
// Only includes .wav files that actually exist in assets/audio at generation time.
type AudioMap = Record<string, any>;

export const phraseAudioMapFemale: AudioMap = {
  u1_p1: require('../assets/audio/female/phrases/u1_p1.wav'),
  u1_p2: require('../assets/audio/female/phrases/u1_p2.wav'),
  u1_p3: require('../assets/audio/female/phrases/u1_p3.wav'),
  u1_p5: require('../assets/audio/female/phrases/u1_p5.wav'),
  u1_p6: require('../assets/audio/female/phrases/u1_p6.wav'),
  u1_p7: require('../assets/audio/female/phrases/u1_p7.wav'),
  u1_p8: require('../assets/audio/female/phrases/u1_p8.wav'),
  u2_p1: require('../assets/audio/female/phrases/u2_p1.wav'),
  u2_p2: require('../assets/audio/female/phrases/u2_p2.wav'),
  u2_p3: require('../assets/audio/female/phrases/u2_p3.wav'),
  u2_p4: require('../assets/audio/female/phrases/u2_p4.wav'),
  u2_p5: require('../assets/audio/female/phrases/u2_p5.wav'),
  u2_p6: require('../assets/audio/female/phrases/u2_p6.wav'),
  u2_p7: require('../assets/audio/female/phrases/u2_p7.wav'),
  u2_p8: require('../assets/audio/female/phrases/u2_p8.wav'),
  u3_p1: require('../assets/audio/female/phrases/u3_p1.wav'),
  u3_p2: require('../assets/audio/female/phrases/u3_p2.wav'),
  u3_p3: require('../assets/audio/female/phrases/u3_p3.wav'),
  u3_p4: require('../assets/audio/female/phrases/u3_p4.wav'),
  u3_p5: require('../assets/audio/female/phrases/u3_p5.wav'),
  u3_p6: require('../assets/audio/female/phrases/u3_p6.wav'),
  u3_p7: require('../assets/audio/female/phrases/u3_p7.wav'),
  u3_p8: require('../assets/audio/female/phrases/u3_p8.wav'),
  u3_p9: require('../assets/audio/female/phrases/u3_p9.wav'),
  u4_p2: require('../assets/audio/female/phrases/u4_p2.wav'),
  u4_p3: require('../assets/audio/female/phrases/u4_p3.wav'),
  u4_p4: require('../assets/audio/female/phrases/u4_p4.wav'),
  u4_p5: require('../assets/audio/female/phrases/u4_p5.wav'),
  u4_p6: require('../assets/audio/female/phrases/u4_p6.wav'),
  u4_p7: require('../assets/audio/female/phrases/u4_p7.wav'),
  u4_p8: require('../assets/audio/female/phrases/u4_p8.wav'),
  u5_p1: require('../assets/audio/female/phrases/u5_p1.wav'),
  u5_p2: require('../assets/audio/female/phrases/u5_p2.wav'),
  u5_p3: require('../assets/audio/female/phrases/u5_p3.wav'),
  u5_p6: require('../assets/audio/female/phrases/u5_p6.wav'),
  u5_p7: require('../assets/audio/female/phrases/u5_p7.wav'),
  u5_p8: require('../assets/audio/female/phrases/u5_p8.wav'),
  u5_p9: require('../assets/audio/female/phrases/u5_p9.wav'),
  u6_p2: require('../assets/audio/female/phrases/u6_p2.wav'),
  u6_p5: require('../assets/audio/female/phrases/u6_p5.wav'),
  u7_p1: require('../assets/audio/female/phrases/u7_p1.wav'),
  u7_p7: require('../assets/audio/female/phrases/u7_p7.wav'),
};

export const phraseAudioMapMale: AudioMap = {};

export const scriptAudioMapFemale: AudioMap = {};

export const scriptAudioMapMale: AudioMap = {};
