// GENERATED OR MODIFIED
type AudioMap = Record<string, any>;

export const phraseAudioMapFemale: AudioMap = {
  // Unit 1: Greetings
  u1_p1: require('../assets/audio/female/phrases/u1_p1.wav'),
  u1_p2: require('../assets/audio/female/phrases/u1_p2.wav'),
  u1_p3: require('../assets/audio/female/phrases/u1_p3.wav'),
  u1_p4: require('../assets/audio/female/phrases/u1_p4.wav'),
  u1_p5: require('../assets/audio/female/phrases/u1_p5.wav'),
  u1_p6: require('../assets/audio/female/phrases/u1_p6.wav'),
  u1_p7: require('../assets/audio/female/phrases/u1_p7.wav'),
  u1_p8: require('../assets/audio/female/phrases/u1_p8.wav'),
  // Unit 2: Introductions
  u2_p1: require('../assets/audio/female/phrases/u2_p1.wav'),
  u2_p2: require('../assets/audio/female/phrases/u2_p2.wav'),
  u2_p3: require('../assets/audio/female/phrases/u2_p3.wav'),
  u2_p4: require('../assets/audio/female/phrases/u2_p4.wav'),
  u2_p5: require('../assets/audio/female/phrases/u2_p5.wav'),
  u2_p6: require('../assets/audio/female/phrases/u2_p6.wav'),
  u2_p7: require('../assets/audio/female/phrases/u2_p7.wav'),
  u2_p8: require('../assets/audio/female/phrases/u2_p8.wav'),
  // Unit 3: Family
  u3_p1: require('../assets/audio/female/phrases/u3_p1.wav'),
  u3_p2: require('../assets/audio/female/phrases/u3_p2.wav'),
  u3_p3: require('../assets/audio/female/phrases/u3_p3.wav'),
  u3_p4: require('../assets/audio/female/phrases/u3_p4.wav'),
  u3_p5: require('../assets/audio/female/phrases/u3_p5.wav'),
  u3_p6: require('../assets/audio/female/phrases/u3_p6.wav'),
  u3_p7: require('../assets/audio/female/phrases/u3_p7.wav'),
  u3_p8: require('../assets/audio/female/phrases/u3_p8.wav'),
  u3_p9: require('../assets/audio/female/phrases/u3_p9.wav'),
  u3_p10: require('../assets/audio/female/phrases/u3_p10.wav'),
  // Unit 4: Daily Basics
  u4_p1: require('../assets/audio/female/phrases/u4_p1.wav'),
  u4_p2: require('../assets/audio/female/phrases/u4_p2.wav'),
  u4_p3: require('../assets/audio/female/phrases/u4_p3.wav'),
  u4_p4: require('../assets/audio/female/phrases/u4_p4.wav'),
  u4_p5: require('../assets/audio/female/phrases/u4_p5.wav'),
  u4_p6: require('../assets/audio/female/phrases/u4_p6.wav'),
  u4_p7: require('../assets/audio/female/phrases/u4_p7.wav'),
  u4_p8: require('../assets/audio/female/phrases/u4_p8.wav'),
  // Unit 5: Food & Drink
  u5_p1: require('../assets/audio/female/phrases/u5_p1.wav'),
  u5_p2: require('../assets/audio/female/phrases/u5_p2.wav'),
  u5_p3: require('../assets/audio/female/phrases/u5_p3.wav'),
  u5_p4: require('../assets/audio/female/phrases/u5_p4.wav'),
  u5_p5: require('../assets/audio/female/phrases/u5_p5.wav'),
  u5_p6: require('../assets/audio/female/phrases/u5_p6.wav'),
  u5_p7: require('../assets/audio/female/phrases/u5_p7.wav'),
  u5_p8: require('../assets/audio/female/phrases/u5_p8.wav'),
  u5_p9: require('../assets/audio/female/phrases/u5_p9.wav'),
  u5_p10: require('../assets/audio/female/phrases/u5_p10.wav'),
  // Unit 6: Yes, No, Thanks
  u6_p1: require('../assets/audio/female/phrases/u6_p1.wav'),
  u6_p2: require('../assets/audio/female/phrases/u6_p2.wav'),
  u6_p3: require('../assets/audio/female/phrases/u6_p3.wav'),
  u6_p4: require('../assets/audio/female/phrases/u6_p4.wav'),
  u6_p5: require('../assets/audio/female/phrases/u6_p5.wav'),
  u6_p6: require('../assets/audio/female/phrases/u6_p6.wav'),
  u6_p7: require('../assets/audio/female/phrases/u6_p7.wav'),
  u6_p8: require('../assets/audio/female/phrases/u6_p8.wav'),
  // Unit 7: Numbers & Money
  u7_p1: require('../assets/audio/female/phrases/u7_p1.wav'),
  u7_p2: require('../assets/audio/female/phrases/u7_p2.wav'),
  u7_p3: require('../assets/audio/female/phrases/u7_p3.wav'),
  u7_p4: require('../assets/audio/female/phrases/u7_p4.wav'),
  u7_p5: require('../assets/audio/female/phrases/u7_p5.wav'),
  u7_p6: require('../assets/audio/female/phrases/u7_p6.wav'),
  u7_p7: require('../assets/audio/female/phrases/u7_p7.wav'),
  u7_p8: require('../assets/audio/female/phrases/u7_p8.wav'),
  u7_p9: require('../assets/audio/female/phrases/u7_p9.wav'),
  u7_p10: require('../assets/audio/female/phrases/u7_p10.wav'),
  u7_p11: require('../assets/audio/female/phrases/u7_p11.wav'),
  u7_p12: require('../assets/audio/female/phrases/u7_p12.wav'),
  // Unit 8: Home Talk
  u8_p1: require('../assets/audio/female/phrases/u8_p1.wav'),
  u8_p2: require('../assets/audio/female/phrases/u8_p2.wav'),
  u8_p3: require('../assets/audio/female/phrases/u8_p3.wav'),
  u8_p4: require('../assets/audio/female/phrases/u8_p4.wav'),
  u8_p5: require('../assets/audio/female/phrases/u8_p5.wav'),
  u8_p6: require('../assets/audio/female/phrases/u8_p6.wav'),
  u8_p7: require('../assets/audio/female/phrases/u8_p7.wav'),
  u8_p8: require('../assets/audio/female/phrases/u8_p8.wav'),
  // Unit 9: Travel
  u9_p1: require('../assets/audio/female/phrases/u9_p1.wav'),
  u9_p2: require('../assets/audio/female/phrases/u9_p2.wav'),
  u9_p3: require('../assets/audio/female/phrases/u9_p3.wav'),
  u9_p4: require('../assets/audio/female/phrases/u9_p4.wav'),
  u9_p5: require('../assets/audio/female/phrases/u9_p5.wav'),
  u9_p6: require('../assets/audio/female/phrases/u9_p6.wav'),
  u9_p7: require('../assets/audio/female/phrases/u9_p7.wav'),
  u9_p8: require('../assets/audio/female/phrases/u9_p8.wav'),
  // Unit 10: Feelings & Help
  u10_p1: require('../assets/audio/female/phrases/u10_p1.wav'),
  u10_p2: require('../assets/audio/female/phrases/u10_p2.wav'),
  u10_p3: require('../assets/audio/female/phrases/u10_p3.wav'),
  u10_p4: require('../assets/audio/female/phrases/u10_p4.wav'),
  u10_p5: require('../assets/audio/female/phrases/u10_p5.wav'),
  u10_p6: require('../assets/audio/female/phrases/u10_p6.wav'),
  u10_p7: require('../assets/audio/female/phrases/u10_p7.wav'),
  u10_p8: require('../assets/audio/female/phrases/u10_p8.wav'),
};
export const phraseAudioMapMale: AudioMap = {
  // Unit 1: Greetings
  u1_p1: require('../assets/audio/male/phrases/u1_p1.wav'),
  u1_p2: require('../assets/audio/male/phrases/u1_p2.wav'),
  u1_p3: require('../assets/audio/male/phrases/u1_p3.wav'),
  u1_p4: require('../assets/audio/male/phrases/u1_p4.wav'),
  u1_p5: require('../assets/audio/male/phrases/u1_p5.wav'),
  u1_p6: require('../assets/audio/male/phrases/u1_p6.wav'),
  u1_p7: require('../assets/audio/male/phrases/u1_p7.wav'),
  u1_p8: require('../assets/audio/male/phrases/u1_p8.wav'),
  // Unit 2: Introductions
  u2_p1: require('../assets/audio/male/phrases/u2_p1.wav'),
  u2_p2: require('../assets/audio/male/phrases/u2_p2.wav'),
  u2_p3: require('../assets/audio/male/phrases/u2_p3.wav'),
  u2_p4: require('../assets/audio/male/phrases/u2_p4.wav'),
  u2_p5: require('../assets/audio/male/phrases/u2_p5.wav'),
  u2_p6: require('../assets/audio/male/phrases/u2_p6.wav'),
  u2_p7: require('../assets/audio/male/phrases/u2_p7.wav'),
  u2_p8: require('../assets/audio/male/phrases/u2_p8.wav'),
  // Unit 3: Family
  u3_p1: require('../assets/audio/male/phrases/u3_p1.wav'),
  u3_p2: require('../assets/audio/male/phrases/u3_p2.wav'),
  u3_p3: require('../assets/audio/male/phrases/u3_p3.wav'),
  u3_p4: require('../assets/audio/male/phrases/u3_p4.wav'),
  u3_p5: require('../assets/audio/male/phrases/u3_p5.wav'),
  u3_p6: require('../assets/audio/male/phrases/u3_p6.wav'),
  u3_p7: require('../assets/audio/male/phrases/u3_p7.wav'),
  u3_p8: require('../assets/audio/male/phrases/u3_p8.wav'),
  u3_p9: require('../assets/audio/male/phrases/u3_p9.wav'),
  u3_p10: require('../assets/audio/male/phrases/u3_p10.wav'),
  // Unit 4: Daily Basics
  u4_p1: require('../assets/audio/male/phrases/u4_p1.wav'),
  u4_p2: require('../assets/audio/male/phrases/u4_p2.wav'),
  u4_p3: require('../assets/audio/male/phrases/u4_p3.wav'),
  u4_p4: require('../assets/audio/male/phrases/u4_p4.wav'),
  u4_p5: require('../assets/audio/male/phrases/u4_p5.wav'),
  u4_p6: require('../assets/audio/male/phrases/u4_p6.wav'),
  u4_p7: require('../assets/audio/male/phrases/u4_p7.wav'),
  u4_p8: require('../assets/audio/male/phrases/u4_p8.wav'),
  // Unit 5: Food & Drink
  u5_p1: require('../assets/audio/male/phrases/u5_p1.wav'),
  u5_p2: require('../assets/audio/male/phrases/u5_p2.wav'),
  u5_p3: require('../assets/audio/male/phrases/u5_p3.wav'),
  u5_p4: require('../assets/audio/male/phrases/u5_p4.wav'),
  u5_p5: require('../assets/audio/male/phrases/u5_p5.wav'),
  u5_p6: require('../assets/audio/male/phrases/u5_p6.wav'),
  u5_p7: require('../assets/audio/male/phrases/u5_p7.wav'),
  u5_p8: require('../assets/audio/male/phrases/u5_p8.wav'),
  u5_p9: require('../assets/audio/male/phrases/u5_p9.wav'),
  u5_p10: require('../assets/audio/male/phrases/u5_p10.wav'),
  // Unit 6: Yes, No, Thanks
  u6_p1: require('../assets/audio/male/phrases/u6_p1.wav'),
  u6_p2: require('../assets/audio/male/phrases/u6_p2.wav'),
  u6_p3: require('../assets/audio/male/phrases/u6_p3.wav'),
  u6_p4: require('../assets/audio/male/phrases/u6_p4.wav'),
  u6_p5: require('../assets/audio/male/phrases/u6_p5.wav'),
  u6_p6: require('../assets/audio/male/phrases/u6_p6.wav'),
  u6_p7: require('../assets/audio/male/phrases/u6_p7.wav'),
  u6_p8: require('../assets/audio/male/phrases/u6_p8.wav'),
  // Unit 7: Numbers & Money
  u7_p1: require('../assets/audio/male/phrases/u7_p1.wav'),
  u7_p2: require('../assets/audio/male/phrases/u7_p2.wav'),
  u7_p3: require('../assets/audio/male/phrases/u7_p3.wav'),
  u7_p4: require('../assets/audio/male/phrases/u7_p4.wav'),
  u7_p5: require('../assets/audio/male/phrases/u7_p5.wav'),
  u7_p6: require('../assets/audio/male/phrases/u7_p6.wav'),
  u7_p7: require('../assets/audio/male/phrases/u7_p7.wav'),
  u7_p8: require('../assets/audio/male/phrases/u7_p8.wav'),
  u7_p9: require('../assets/audio/male/phrases/u7_p9.wav'),
  u7_p10: require('../assets/audio/male/phrases/u7_p10.wav'),
  u7_p11: require('../assets/audio/male/phrases/u7_p11.wav'),
  u7_p12: require('../assets/audio/male/phrases/u7_p12.wav'),
  // Unit 8: Home Talk
  u8_p1: require('../assets/audio/male/phrases/u8_p1.wav'),
  u8_p2: require('../assets/audio/male/phrases/u8_p2.wav'),
  u8_p3: require('../assets/audio/male/phrases/u8_p3.wav'),
  u8_p4: require('../assets/audio/male/phrases/u8_p4.wav'),
  u8_p5: require('../assets/audio/male/phrases/u8_p5.wav'),
  u8_p6: require('../assets/audio/male/phrases/u8_p6.wav'),
  u8_p7: require('../assets/audio/male/phrases/u8_p7.wav'),
  u8_p8: require('../assets/audio/male/phrases/u8_p8.wav'),
  // Unit 9: Travel
  u9_p1: require('../assets/audio/male/phrases/u9_p1.wav'),
  u9_p2: require('../assets/audio/male/phrases/u9_p2.wav'),
  u9_p3: require('../assets/audio/male/phrases/u9_p3.wav'),
  u9_p4: require('../assets/audio/male/phrases/u9_p4.wav'),
  u9_p5: require('../assets/audio/male/phrases/u9_p5.wav'),
  u9_p6: require('../assets/audio/male/phrases/u9_p6.wav'),
  u9_p7: require('../assets/audio/male/phrases/u9_p7.wav'),
  u9_p8: require('../assets/audio/male/phrases/u9_p8.wav'),
  // Unit 10: Feelings & Help
  u10_p1: require('../assets/audio/male/phrases/u10_p1.wav'),
  u10_p2: require('../assets/audio/male/phrases/u10_p2.wav'),
  u10_p3: require('../assets/audio/male/phrases/u10_p3.wav'),
  u10_p4: require('../assets/audio/male/phrases/u10_p4.wav'),
  u10_p5: require('../assets/audio/male/phrases/u10_p5.wav'),
  u10_p6: require('../assets/audio/male/phrases/u10_p6.wav'),
  u10_p7: require('../assets/audio/male/phrases/u10_p7.wav'),
  u10_p8: require('../assets/audio/male/phrases/u10_p8.wav'),
};

export const scriptAudioMapFemale: AudioMap = {
  // Vowels
  vowel_a: require('../assets/audio/female/script/vowel_a.wav'),
  vowel_aa: require('../assets/audio/female/script/vowel_aa.wav'),
  vowel_i: require('../assets/audio/female/script/vowel_i.wav'),
  vowel_ee: require('../assets/audio/female/script/vowel_ee.wav'),
  vowel_u: require('../assets/audio/female/script/vowel_u.wav'),
  vowel_oo: require('../assets/audio/female/script/vowel_oo.wav'),
  vowel_e: require('../assets/audio/female/script/vowel_e.wav'),
  vowel_ai: require('../assets/audio/female/script/vowel_ai.wav'),
  vowel_o: require('../assets/audio/female/script/vowel_o.wav'),
  vowel_au: require('../assets/audio/female/script/vowel_au.wav'),
  // Consonants group 1
  cons_ka: require('../assets/audio/female/script/cons_ka.wav'),
  cons_kha: require('../assets/audio/female/script/cons_kha.wav'),
  cons_ga: require('../assets/audio/female/script/cons_ga.wav'),
  cons_gha: require('../assets/audio/female/script/cons_gha.wav'),
  cons_nga: require('../assets/audio/female/script/cons_nga.wav'),
  // Group 2
  cons_cha: require('../assets/audio/female/script/cons_cha.wav'),
  cons_chha: require('../assets/audio/female/script/cons_chha.wav'),
  cons_ja: require('../assets/audio/female/script/cons_ja.wav'),
  cons_jha: require('../assets/audio/female/script/cons_jha.wav'),
  cons_nya: require('../assets/audio/female/script/cons_nya.wav'),
  // Group 3 (retroflex)
  cons_Ta: require('../assets/audio/female/script/cons_Ta.wav'),
  cons_Tha: require('../assets/audio/female/script/cons_Tha.wav'),
  cons_Da: require('../assets/audio/female/script/cons_Da.wav'),
  cons_Dha: require('../assets/audio/female/script/cons_Dha.wav'),
  cons_Na: require('../assets/audio/female/script/cons_Na.wav'),
  // Group 4 (dental)
  cons_ta: require('../assets/audio/female/script/cons_ta.wav'),
  cons_tha: require('../assets/audio/female/script/cons_tha.wav'),
  cons_da: require('../assets/audio/female/script/cons_da.wav'),
  cons_dha: require('../assets/audio/female/script/cons_dha.wav'),
  cons_na: require('../assets/audio/female/script/cons_na.wav'),
  // Group 5 (labial)
  cons_pa: require('../assets/audio/female/script/cons_pa.wav'),
  cons_pha: require('../assets/audio/female/script/cons_pha.wav'),
  cons_ba: require('../assets/audio/female/script/cons_ba.wav'),
  cons_bha: require('../assets/audio/female/script/cons_bha.wav'),
  cons_ma: require('../assets/audio/female/script/cons_ma.wav'),
  // Group 6 (semi-vowels)
  cons_ya: require('../assets/audio/female/script/cons_ya.wav'),
  cons_ra: require('../assets/audio/female/script/cons_ra.wav'),
  cons_la: require('../assets/audio/female/script/cons_la.wav'),
  cons_wa: require('../assets/audio/female/script/cons_wa.wav'),
  // Group 7 (sibilants)
  cons_sha: require('../assets/audio/female/script/cons_sha.wav'),
  cons_Sha: require('../assets/audio/female/script/cons_Sha.wav'),
  cons_sa: require('../assets/audio/female/script/cons_sa.wav'),
  cons_ha: require('../assets/audio/female/script/cons_ha.wav'),
  // Matras
  matra_ka: require('../assets/audio/female/script/matra_ka.wav'),
  matra_kaa: require('../assets/audio/female/script/matra_kaa.wav'),
  matra_ki: require('../assets/audio/female/script/matra_ki.wav'),
  matra_kee: require('../assets/audio/female/script/matra_kee.wav'),
  matra_ku: require('../assets/audio/female/script/matra_ku.wav'),
  matra_koo: require('../assets/audio/female/script/matra_koo.wav'),
  matra_ke: require('../assets/audio/female/script/matra_ke.wav'),
  matra_kai: require('../assets/audio/female/script/matra_kai.wav'),
  matra_ko: require('../assets/audio/female/script/matra_ko.wav'),
  matra_kau: require('../assets/audio/female/script/matra_kau.wav'),
  // Matras (Kha)
  matra_kha: require('../assets/audio/female/script/matra_kha.wav'),
  matra_khaa: require('../assets/audio/female/script/matra_khaa.wav'),
  matra_khi: require('../assets/audio/female/script/matra_khi.wav'),
  matra_khee: require('../assets/audio/female/script/matra_khee.wav'),
  matra_khu: require('../assets/audio/female/script/matra_khu.wav'),
  matra_khoo: require('../assets/audio/female/script/matra_khoo.wav'),
  matra_khe: require('../assets/audio/female/script/matra_khe.wav'),
  matra_khai: require('../assets/audio/female/script/matra_khai.wav'),
  matra_kho: require('../assets/audio/female/script/matra_kho.wav'),
  matra_khau: require('../assets/audio/female/script/matra_khau.wav'),
  // Matras (Ga)
  matra_ga: require('../assets/audio/female/script/matra_ga.wav'),
  matra_gaa: require('../assets/audio/female/script/matra_gaa.wav'),
  matra_gi: require('../assets/audio/female/script/matra_gi.wav'),
  matra_gee: require('../assets/audio/female/script/matra_gee.wav'),
  matra_gu: require('../assets/audio/female/script/matra_gu.wav'),
  matra_goo: require('../assets/audio/female/script/matra_goo.wav'),
  matra_ge: require('../assets/audio/female/script/matra_ge.wav'),
  matra_gai: require('../assets/audio/female/script/matra_gai.wav'),
  matra_go: require('../assets/audio/female/script/matra_go.wav'),
  matra_gau: require('../assets/audio/female/script/matra_gau.wav'),
  // Matras (Gha)
  matra_gha: require('../assets/audio/female/script/matra_gha.wav'),
  matra_ghaa: require('../assets/audio/female/script/matra_ghaa.wav'),
  matra_ghi: require('../assets/audio/female/script/matra_ghi.wav'),
  matra_ghee: require('../assets/audio/female/script/matra_ghee.wav'),
  matra_ghu: require('../assets/audio/female/script/matra_ghu.wav'),
  matra_ghoo: require('../assets/audio/female/script/matra_ghoo.wav'),
  matra_ghe: require('../assets/audio/female/script/matra_ghe.wav'),
  matra_ghai: require('../assets/audio/female/script/matra_ghai.wav'),
  matra_gho: require('../assets/audio/female/script/matra_gho.wav'),
  matra_ghau: require('../assets/audio/female/script/matra_ghau.wav'),
  // Matras (Cha)
  matra_cha: require('../assets/audio/female/script/matra_cha.wav'),
  matra_chaa: require('../assets/audio/female/script/matra_chaa.wav'),
  matra_chi: require('../assets/audio/female/script/matra_chi.wav'),
  matra_chee: require('../assets/audio/female/script/matra_chee.wav'),
  matra_chu: require('../assets/audio/female/script/matra_chu.wav'),
  matra_choo: require('../assets/audio/female/script/matra_choo.wav'),
  matra_che: require('../assets/audio/female/script/matra_che.wav'),
  matra_chai: require('../assets/audio/female/script/matra_chai.wav'),
  matra_cho: require('../assets/audio/female/script/matra_cho.wav'),
  matra_chau: require('../assets/audio/female/script/matra_chau.wav'),
  // Syllables
  syl_maa: require('../assets/audio/female/script/syl_maa.wav'),
  syl_naa: require('../assets/audio/female/script/syl_naa.wav'),
  syl_raa: require('../assets/audio/female/script/syl_raa.wav'),
  syl_baa: require('../assets/audio/female/script/syl_baa.wav'),
  syl_kee: require('../assets/audio/female/script/syl_kee.wav'),
  syl_nee: require('../assets/audio/female/script/syl_nee.wav'),
  syl_pu: require('../assets/audio/female/script/syl_pu.wav'),
  syl_re: require('../assets/audio/female/script/syl_re.wav'),
  // Words
  word_ma: require('../assets/audio/female/script/word_ma.wav'),
  word_ghar: require('../assets/audio/female/script/word_ghar.wav'),
  word_baabaa: require('../assets/audio/female/script/word_baabaa.wav'),
  word_mamee: require('../assets/audio/female/script/word_mamee.wav'),
  word_maa: require('../assets/audio/female/script/word_maa.wav'),
  word_paanee: require('../assets/audio/female/script/word_paanee.wav'),
  word_khaanaa: require('../assets/audio/female/script/word_khaanaa.wav'),
  word_raamro: require('../assets/audio/female/script/word_raamro.wav'),
  word_saathee: require('../assets/audio/female/script/word_saathee.wav'),
  word_aama: require('../assets/audio/female/script/word_aama.wav'),
  word_buwa: require('../assets/audio/female/script/word_buwa.wav'),
  word_namaste: require('../assets/audio/female/script/word_namaste.wav'),
  word_dhanyabaad: require('../assets/audio/female/script/word_dhanyabaad.wav'),
  word_hajur: require('../assets/audio/female/script/word_hajur.wav'),
  word_hoina: require('../assets/audio/female/script/word_hoina.wav'),
  word_thikchhha: require('../assets/audio/female/script/word_thikchhha.wav'),
  // Phrases
  phrase_namaste: require('../assets/audio/female/script/phrase_namaste.wav'),
  phrase_ma_thik_chhu: require('../assets/audio/female/script/phrase_ma_thik_chhu.wav'),
  phrase_malai_paani: require('../assets/audio/female/script/phrase_malai_paani.wav'),
  phrase_ma_ghar: require('../assets/audio/female/script/phrase_ma_ghar.wav'),
  phrase_dhanyabaad: require('../assets/audio/female/script/phrase_dhanyabaad.wav'),
};
export const scriptAudioMapMale: AudioMap = {
  // Vowels
  vowel_a: require('../assets/audio/male/script/vowel_a.wav'),
  vowel_aa: require('../assets/audio/male/script/vowel_aa.wav'),
  vowel_i: require('../assets/audio/male/script/vowel_i.wav'),
  vowel_ee: require('../assets/audio/male/script/vowel_ee.wav'),
  vowel_u: require('../assets/audio/male/script/vowel_u.wav'),
  vowel_oo: require('../assets/audio/male/script/vowel_oo.wav'),
  vowel_e: require('../assets/audio/male/script/vowel_e.wav'),
  vowel_ai: require('../assets/audio/male/script/vowel_ai.wav'),
  vowel_o: require('../assets/audio/male/script/vowel_o.wav'),
  vowel_au: require('../assets/audio/male/script/vowel_au.wav'),
  // Consonants group 1
  cons_ka: require('../assets/audio/male/script/cons_ka.wav'),
  cons_kha: require('../assets/audio/male/script/cons_kha.wav'),
  cons_ga: require('../assets/audio/male/script/cons_ga.wav'),
  cons_gha: require('../assets/audio/male/script/cons_gha.wav'),
  cons_nga: require('../assets/audio/male/script/cons_nga.wav'),
  // Group 2
  cons_cha: require('../assets/audio/male/script/cons_cha.wav'),
  cons_chha: require('../assets/audio/male/script/cons_chha.wav'),
  cons_ja: require('../assets/audio/male/script/cons_ja.wav'),
  cons_jha: require('../assets/audio/male/script/cons_jha.wav'),
  cons_nya: require('../assets/audio/male/script/cons_nya.wav'),
  // Group 3 (retroflex)
  cons_Ta: require('../assets/audio/male/script/cons_Ta.wav'),
  cons_Tha: require('../assets/audio/male/script/cons_Tha.wav'),
  cons_Da: require('../assets/audio/male/script/cons_Da.wav'),
  cons_Dha: require('../assets/audio/male/script/cons_Dha.wav'),
  cons_Na: require('../assets/audio/male/script/cons_Na.wav'),
  // Group 4 (dental)
  cons_ta: require('../assets/audio/male/script/cons_ta.wav'),
  cons_tha: require('../assets/audio/male/script/cons_tha.wav'),
  cons_da: require('../assets/audio/male/script/cons_da.wav'),
  cons_dha: require('../assets/audio/male/script/cons_dha.wav'),
  cons_na: require('../assets/audio/male/script/cons_na.wav'),
  // Group 5 (labial)
  cons_pa: require('../assets/audio/male/script/cons_pa.wav'),
  cons_pha: require('../assets/audio/male/script/cons_pha.wav'),
  cons_ba: require('../assets/audio/male/script/cons_ba.wav'),
  cons_bha: require('../assets/audio/male/script/cons_bha.wav'),
  cons_ma: require('../assets/audio/male/script/cons_ma.wav'),
  // Group 6 (semi-vowels)
  cons_ya: require('../assets/audio/male/script/cons_ya.wav'),
  cons_ra: require('../assets/audio/male/script/cons_ra.wav'),
  cons_la: require('../assets/audio/male/script/cons_la.wav'),
  cons_wa: require('../assets/audio/male/script/cons_wa.wav'),
  // Group 7 (sibilants)
  cons_sha: require('../assets/audio/male/script/cons_sha.wav'),
  cons_Sha: require('../assets/audio/male/script/cons_Sha.wav'),
  cons_sa: require('../assets/audio/male/script/cons_sa.wav'),
  cons_ha: require('../assets/audio/male/script/cons_ha.wav'),
  // Matras
  matra_ka: require('../assets/audio/male/script/matra_ka.wav'),
  matra_kaa: require('../assets/audio/male/script/matra_kaa.wav'),
  matra_ki: require('../assets/audio/male/script/matra_ki.wav'),
  matra_kee: require('../assets/audio/male/script/matra_kee.wav'),
  matra_ku: require('../assets/audio/male/script/matra_ku.wav'),
  matra_koo: require('../assets/audio/male/script/matra_koo.wav'),
  matra_ke: require('../assets/audio/male/script/matra_ke.wav'),
  matra_kai: require('../assets/audio/male/script/matra_kai.wav'),
  matra_ko: require('../assets/audio/male/script/matra_ko.wav'),
  matra_kau: require('../assets/audio/male/script/matra_kau.wav'),
  // Matras (Kha)
  matra_kha: require('../assets/audio/male/script/matra_kha.wav'),
  matra_khaa: require('../assets/audio/male/script/matra_khaa.wav'),
  matra_khi: require('../assets/audio/male/script/matra_khi.wav'),
  matra_khee: require('../assets/audio/male/script/matra_khee.wav'),
  matra_khu: require('../assets/audio/male/script/matra_khu.wav'),
  matra_khoo: require('../assets/audio/male/script/matra_khoo.wav'),
  matra_khe: require('../assets/audio/male/script/matra_khe.wav'),
  matra_khai: require('../assets/audio/male/script/matra_khai.wav'),
  matra_kho: require('../assets/audio/male/script/matra_kho.wav'),
  matra_khau: require('../assets/audio/male/script/matra_khau.wav'),
  // Matras (Ga)
  matra_ga: require('../assets/audio/male/script/matra_ga.wav'),
  matra_gaa: require('../assets/audio/male/script/matra_gaa.wav'),
  matra_gi: require('../assets/audio/male/script/matra_gi.wav'),
  matra_gee: require('../assets/audio/male/script/matra_gee.wav'),
  matra_gu: require('../assets/audio/male/script/matra_gu.wav'),
  matra_goo: require('../assets/audio/male/script/matra_goo.wav'),
  matra_ge: require('../assets/audio/male/script/matra_ge.wav'),
  matra_gai: require('../assets/audio/male/script/matra_gai.wav'),
  matra_go: require('../assets/audio/male/script/matra_go.wav'),
  matra_gau: require('../assets/audio/male/script/matra_gau.wav'),
  // Matras (Gha)
  matra_gha: require('../assets/audio/male/script/matra_gha.wav'),
  matra_ghaa: require('../assets/audio/male/script/matra_ghaa.wav'),
  matra_ghi: require('../assets/audio/male/script/matra_ghi.wav'),
  matra_ghee: require('../assets/audio/male/script/matra_ghee.wav'),
  matra_ghu: require('../assets/audio/male/script/matra_ghu.wav'),
  matra_ghoo: require('../assets/audio/male/script/matra_ghoo.wav'),
  matra_ghe: require('../assets/audio/male/script/matra_ghe.wav'),
  matra_ghai: require('../assets/audio/male/script/matra_ghai.wav'),
  matra_gho: require('../assets/audio/male/script/matra_gho.wav'),
  matra_ghau: require('../assets/audio/male/script/matra_ghau.wav'),
  // Matras (Cha)
  matra_cha: require('../assets/audio/male/script/matra_cha.wav'),
  matra_chaa: require('../assets/audio/male/script/matra_chaa.wav'),
  matra_chi: require('../assets/audio/male/script/matra_chi.wav'),
  matra_chee: require('../assets/audio/male/script/matra_chee.wav'),
  matra_chu: require('../assets/audio/male/script/matra_chu.wav'),
  matra_choo: require('../assets/audio/male/script/matra_choo.wav'),
  matra_che: require('../assets/audio/male/script/matra_che.wav'),
  matra_chai: require('../assets/audio/male/script/matra_chai.wav'),
  matra_cho: require('../assets/audio/male/script/matra_cho.wav'),
  matra_chau: require('../assets/audio/male/script/matra_chau.wav'),
  // Syllables
  syl_maa: require('../assets/audio/male/script/syl_maa.wav'),
  syl_naa: require('../assets/audio/male/script/syl_naa.wav'),
  syl_raa: require('../assets/audio/male/script/syl_raa.wav'),
  syl_baa: require('../assets/audio/male/script/syl_baa.wav'),
  syl_kee: require('../assets/audio/male/script/syl_kee.wav'),
  syl_nee: require('../assets/audio/male/script/syl_nee.wav'),
  syl_pu: require('../assets/audio/male/script/syl_pu.wav'),
  syl_re: require('../assets/audio/male/script/syl_re.wav'),
  // Words
  word_ma: require('../assets/audio/male/script/word_ma.wav'),
  word_ghar: require('../assets/audio/male/script/word_ghar.wav'),
  word_baabaa: require('../assets/audio/male/script/word_baabaa.wav'),
  word_mamee: require('../assets/audio/male/script/word_mamee.wav'),
  word_maa: require('../assets/audio/male/script/word_maa.wav'),
  word_paanee: require('../assets/audio/male/script/word_paanee.wav'),
  word_khaanaa: require('../assets/audio/male/script/word_khaanaa.wav'),
  word_raamro: require('../assets/audio/male/script/word_raamro.wav'),
  word_saathee: require('../assets/audio/male/script/word_saathee.wav'),
  word_aama: require('../assets/audio/male/script/word_aama.wav'),
  word_buwa: require('../assets/audio/male/script/word_buwa.wav'),
  word_namaste: require('../assets/audio/male/script/word_namaste.wav'),
  word_dhanyabaad: require('../assets/audio/male/script/word_dhanyabaad.wav'),
  word_hajur: require('../assets/audio/male/script/word_hajur.wav'),
  word_hoina: require('../assets/audio/male/script/word_hoina.wav'),
  word_thikchhha: require('../assets/audio/male/script/word_thikchhha.wav'),
  // Phrases
  phrase_namaste: require('../assets/audio/male/script/phrase_namaste.wav'),
  phrase_ma_thik_chhu: require('../assets/audio/male/script/phrase_ma_thik_chhu.wav'),
  phrase_malai_paani: require('../assets/audio/male/script/phrase_malai_paani.wav'),
  phrase_ma_ghar: require('../assets/audio/male/script/phrase_ma_ghar.wav'),
  phrase_dhanyabaad: require('../assets/audio/male/script/phrase_dhanyabaad.wav'),
};
