#!/usr/bin/env node
// generateAudioMap.js — regenerates constants/audioMap.ts using only files that actually exist on disk
const fs = require('fs');
const path = require('path');

const AUDIO_ROOT = path.join(__dirname, '../assets/audio');
const OUTPUT = path.join(__dirname, '../constants/audioMap.ts');

function getExistingKeys(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.wav'))
    .map(f => f.replace('.wav', ''))
    .sort();
}

function buildMap(keys, relPath) {
  if (keys.length === 0) return '{}';
  const entries = keys.map(k => `  ${k}: require('${relPath}/${k}.wav'),`).join('\n');
  return `{\n${entries}\n}`;
}

const femalePhraseKeys  = getExistingKeys(path.join(AUDIO_ROOT, 'female/phrases'));
const malePhraseKeys    = getExistingKeys(path.join(AUDIO_ROOT, 'male/phrases'));
const femaleScriptKeys  = getExistingKeys(path.join(AUDIO_ROOT, 'female/script'));
const maleScriptKeys    = getExistingKeys(path.join(AUDIO_ROOT, 'male/script'));

const output = `// AUTO-GENERATED by scripts/generateAudioMap.js — DO NOT EDIT MANUALLY
// Run: node scripts/generateAudioMap.js  (or npm run gen:audio)
// Only includes .wav files that actually exist in assets/audio at generation time.
type AudioMap = Record<string, any>;

export const phraseAudioMapFemale: AudioMap = ${buildMap(femalePhraseKeys, '../assets/audio/female/phrases')};

export const phraseAudioMapMale: AudioMap = ${buildMap(malePhraseKeys, '../assets/audio/male/phrases')};

export const scriptAudioMapFemale: AudioMap = ${buildMap(femaleScriptKeys, '../assets/audio/female/script')};

export const scriptAudioMapMale: AudioMap = ${buildMap(maleScriptKeys, '../assets/audio/male/script')};
`;

fs.writeFileSync(OUTPUT, output, 'utf8');
console.log(`✅ audioMap.ts regenerated`);
console.log(`   female phrases : ${femalePhraseKeys.length} files`);
console.log(`   male   phrases : ${malePhraseKeys.length} files`);
console.log(`   female script  : ${femaleScriptKeys.length} files`);
console.log(`   male   script  : ${maleScriptKeys.length} files`);
const missing = [];
const ALL_PHRASE_KEYS = [...new Set([...femalePhraseKeys, ...malePhraseKeys])];
// log any keys present for one voice but not the other
femalePhraseKeys.forEach(k => { if (!malePhraseKeys.includes(k)) missing.push(`male/phrases/${k}.wav`); });
malePhraseKeys.forEach(k => { if (!femalePhraseKeys.includes(k)) missing.push(`female/phrases/${k}.wav`); });
femaleScriptKeys.forEach(k => { if (!maleScriptKeys.includes(k)) missing.push(`male/script/${k}.wav`); });
maleScriptKeys.forEach(k => { if (!femaleScriptKeys.includes(k)) missing.push(`female/script/${k}.wav`); });
if (missing.length) {
  console.log(`\n⚠️  Missing counterparts (present for one voice, not the other):`);
  missing.forEach(m => console.log(`   ${m}`));
}
